name: Do things
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      url: ${{ steps.step1.outputs.url }} # map step output to job output
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set selected color
        run: echo '::set-output name=SELECTED_COLOR::green'
        id: random-color-generator
      - name: set second
        run: echo "::set-output name=action_fruit::strawberry"
      - name: Get color
        run: echo "The selected color is ${{ steps.random-color-generator.outputs.SELECTED_COLOR }}"
      - name: Echo file
        run: echo "test 1234567890" >> file.txt        
      - uses: jdvr/action-add-comment@main
        with:
          comment: 'Current build $BUILD_NUMBER has passed ✅'
        env:
          BUILD_NUMBER: 1234
          GITHUB_TOKEN: "{{ secrets.GITHUB_TOKEN }}"
