name: Do things
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      url: ${{ steps.step1.outputs.url }} # map step output to job output
    steps:
      - id: step1
        name: send url to other job
        run: echo "::set-output name=url::https://google.com"
