name: Do things
on: pull_request
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      url: ${{ steps.step1.outputs.url }} # map step output to job output
    steps:
      - name: Checkout
        uses: actions/checkout@v2     
      - uses: jdvr/action-add-comment@main
        with:
          comment: "Current build $BUILD_NUMBER has passed ✅"
        env:
          BUILD_NUMBER: 1234
          GITHUB_TOKEN: ${{github.token}}
