name: Do things
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      url: ${{ steps.step1.outputs.url }} # map step output to job output
    steps:
      - name: Set selected color
        run: echo '::set-output name=SELECTED_COLOR::green'
        id: random-color-generator
      - name: set second
        run: echo "::set-output name=action_fruit::strawberry"
      - name: Get color
        run: echo "The selected color is ${{ steps.random-color-generator.outputs.SELECTED_COLOR }}"
      - name: Echo file
        run: echo "test 1234567890" >> file.txt        
      - uses: edwardgeorge/file-outputs-action@main
        with:
          files: |
            output1=file.txt
    
