name: Print contents of secret
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      url: ${{ steps.step1.outputs.url }} # map step output to job output
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run File
        run: bash -x runme.sh
#       - uses: zattoo/output@v1
#         with:
#           token:  ${{ secrets.GITHUB_TOKEN }}
#           sources: 'dimi/HELLO_WORLD.md'
