
name: Do things 222
on: pull_request
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      url: ${{ steps.step1.outputs.url }} # map step output to job output
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Echo file
        run: echo "test 1234567890" >> file.md        
      - uses: zattoo/output@v1
        with:
          token:  ${{github.token}}
          sources: 'file.md'
